[package]
name = "read_bno055"
version = "0.1.0"
authors = ["chrism"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mint = "0.5.6"
linux-embedded-hal = "0.3"
#linux-embedded-hal = "0.4.0-alpha.0"
bno055 = "0.3.2"
